### ISSUE TITLE
jexpr-encoder-utils-0.2.2.jar中没有主清单属性

### ISSUE THREAD

**Issue by M0untainShley** [woodpecker-appstore/jexpr-encoder-utils#1]
环境 jdk8u66，8u202，java -jar x.jar 这种形式运行jar包提示没有主清单属性，请问师傅这个问题怎么解决

**Comment by m4ra7h0n** [comment]
> 环境 jdk8u66，8u202，java -jar x.jar 这种形式运行jar包提示没有主清单属性，请问师傅这个问题怎么解决

所以是怎么解决的

**Comment by c0ny1** [comment]
这是插件无法单独运行,需要下载[框架](https://github.com/woodpecker-framework/woodpecker-framework-release)，然后把插件下载到plugin目录 @x-j-j
